post_install() {
    XDG_DATA_DIRS+=":/usr/share/glib-2.0/schemas"
    flatpak install -y --noninteractive /usr/share/jade-gui/jade-gui.flatpak
}

post_upgrade() {
    XDG_DATA_DIRS+=":/usr/share/glib-2.0/schemas"
    flatpak install -y --noninteractive /usr/share/jade-gui/jade-gui.flatpak
}

post_remove() {
    XDG_DATA_DIRS+=":/usr/share/glib-2.0/schemas"
    flatpak remove -y --noninteractive al.getcryst.jadegui
}
